version: '2'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - api
      - node

  api:
    image: nanoninja/php-fpm:7.2
    expose:
      - "9000"
    volumes:
      - ./api:/var/www/html

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/:/home/node/app
    expose:
      - "9009"
    command: "./node_modules/webpack-dev-server/bin/webpack-dev-server.js
                --config webpack.config.js
                --progress
                --content-base ./public
                --output-public-path /build/"
