documents_index:
    path: /api/documents
    methods: GET
    controller: App\Controller\ApiDocumentController::index

documents_by_type_index:
    path: /api/document_types/{id}/documents
    methods: GET
    controller: App\Controller\ApiDocumentController::indexByType

documents_create:
    path: /api/documents
    methods: POST
    controller: App\Controller\ApiDocumentController::create

documents_delete:
    path: /api/documents/{id}
    methods: DELETE
    controller: App\Controller\ApiDocumentController::delete

document_types_index:
    path: /api/document_types
    methods: GET
    controller: App\Controller\ApiDocumentTypeController::index
